package: binstar

platform:
  - linux-64
  - osx-64
  - win-64

engine:
 - python=2.7

install:
  - conda install pip setuptools
  - pip install coverage mock
  - python setup.py develop

test:
  - python binstar_client/tests/runtests.py

script:
  - conda build conda.recipe

build_targets: [conda]

---
# Upload python sdist for python2 only since it does not depend on the python version
engine: python=2.7
platform: linux-64
env: PYPI=1
build_targets: [pypi]
script:
  - conda build .
  - python setup.py sdist
