package: binstar

platform:
  - linux-32
  - linux-64
  - osx-64
  - win-32
  - win-64

engine:
 - python=2.7
 - python=3.4
 - python=3.5

install:
  - conda install pip setuptools clyent pillow
  - pip install coverage==3.7.1 mock
  - python setup.py develop

test:
  - conda config --add channels https://conda.anaconda.org/t/ha-e3f51724-731d-45ea-bbb7-853fdda42c11/binstar
  - conda install -y nbformat anaconda_project
  - python binstar_client/tests/runtests.py

script:
  - conda build conda.recipe

build_targets: [conda]

# ---
# Upload python sdist for python2 only since it does not depend on the python version
# engine: python=2.7
# platform: linux-64
# env: PYPI=1
# build_targets: [pypi]
# script:
#   - conda build .
#   - python setup.py sdist
