package: binstar
engine:
 - python=2.7
 - python=3.3

install:
  - pip install -r requirements.txt
  - pip install coverage mock

test:
  - python setup.py develop
  - python binstar_client/tests/runtests.py

script:
  - conda build .

build_targets: [conda]

---
# Upload python sdist for python2 only since it does not depend on the python version
engine: python=2.7
build_artifacts: dist/binstar*.tar.gz
build_targets: [conda, pypi]
script:
  - conda build .
  - python setup.py sdist

