package: binstar

platform:
  - linux-64
  - osx-64

engine:
 - python=2.7

install:
  - pip install -r requirements.txt
  - pip install coverage mock

test:
  - python setup.py develop
  - python binstar_client/tests/runtests.py

before_script:
  - touch build.sh # FIX: for conda issue

script:
  - conda build .

build_targets: [conda]

---
# Upload python sdist for python2 only since it does not depend on the python version
engine: python=2.7
platform: linux-64
build_targets: [conda]
script:
  - conda build .
  - python setup.py sdist

