package: binstar

platform:
  - linux-64
  - osx-64
  - win-64

engine:
 - python=2.7
 - python=3.4

install:
  - conda install pip setuptools clyent pillow
  - pip install coverage==3.7.1 mock
  - python setup.py develop

test:
  - conda install -y nbformat
  - python binstar_client/tests/runtests.py

script:
  - conda build conda.recipe

build_targets: [conda]

# ---
# Upload python sdist for python2 only since it does not depend on the python version
# engine: python=2.7
# platform: linux-64
# env: PYPI=1
# build_targets: [pypi]
# script:
#   - conda build .
#   - python setup.py sdist
