# https://travis-ci.org/Anaconda-Platform/anaconda-client

language: python
sudo: false
branches:
  only:
    - develop

env:
  global:
    # Environment variables used by astropy helpers
    - CONDA_CHANNELS="https://conda.anaconda.org/t/an-1126452d-8e3d-439a-9763-03b5696f4f97/binstar conda-kapsel"
    - CONDA_DEPENDENCIES="pip setuptools=23.0.0  clyent pillow psutil nbformat anaconda-project coverage==3.7.1 mock "

matrix:
  include:
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.4
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.5

install:
  # Use Astropy ci helpers for initial setup
  - git clone git://github.com/astropy/ci-helpers.git --depth=1
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
  - python setup.py develop

script:
  - python binstar_client/tests/runtests.py

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - coveralls
