{% set data = load_setuptools()%}
package:
  name: anaconda-client
  version: {{data.get('version')}}

build: {}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - clyent
    - requests
    - pyyaml
    - dateutil
    - pytz

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
